### ISSUE TITLE
Backend Basic setup

### ISSUE THREAD

**Issue by V1NAY8** [nerds-amp-mods/Hackathon-Login-Starter-Pack#1]
# Initial Thoughts
- Frontend Folder (Leave it unattended as of now)
- Backend Folder (Microservices with flask)
- One Step Deployable for Backend (.sh or .bat or DockerFile) (Because this is the main aim of the project)
- Add Github actions

**Comment by sakethramanujam** [comment]
adding github actions would be pre-emptive at this point, should we phase it and concentrate on getting things done?
and also add resources may be?

**Comment by V1NAY8** [comment]
Yes please
